#!/usr/bin/env bash
#
# P2-15 pre-commit hook 安装脚本
#
# 用途：把 scripts/lint.sh 安装为 .git/hooks/pre-commit，使每次 git commit 自动跑 lint
#
# 用法：
#   ./scripts/install-hooks.sh          # 安装 pre-commit
#   ./scripts/install-hooks.sh --uninstall  # 卸载
#
# 注：本项目无 git 仓库（IDE-only 模式）时跳过，仅给出友好提示

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$ROOT_DIR/.git/hooks"
HOOK_TARGET="$HOOKS_DIR/pre-commit"
HOOK_SRC="$SCRIPT_DIR/lint.sh"

uninstall() {
  if [ -f "$HOOK_TARGET" ]; then
    rm -f "$HOOK_TARGET"
    echo "[hooks] removed pre-commit hook"
  else
    echo "[hooks] no pre-commit hook installed, nothing to remove"
  fi
  exit 0
}

if [ "${1:-}" = "--uninstall" ]; then
  uninstall
fi

if [ ! -d "$ROOT_DIR/.git" ]; then
  echo "[hooks] .git not found in $ROOT_DIR, skip install"
  echo "[hooks] （项目无 git 仓库，可在 IDE 提交时跑 lint）"
  exit 0
fi

mkdir -p "$HOOKS_DIR"

# 检查是否已安装（幂等）
if [ -f "$HOOK_TARGET" ] && grep -q "scripts/lint.sh" "$HOOK_TARGET"; then
  echo "[hooks] pre-commit hook already installed"
  exit 0
fi

cat > "$HOOK_TARGET" <<EOF
#!/usr/bin/env bash
#
# Auto-generated by scripts/install-hooks.sh
# P2-15 hvigor lint pre-commit hook
#
exec "$ROOT_DIR/scripts/lint.sh"
EOF

chmod +x "$HOOK_TARGET"
echo "[hooks] pre-commit hook installed at $HOOK_TARGET"
echo "[hooks] run './scripts/install-hooks.sh --uninstall' to remove"